### ISSUE TITLE
黑色背景，没效果android:visibility="gone"  

### ISSUE THREAD

**Issue by jiangcb** [Jay-Goo/WaveLineView#1]
<jaygoo.widget.wlv.WaveLineView
                android:id="@+id/waveLineView"
                android:visibility="gone"
                android:layout_width="match_parent"
                android:layout_height="120dp" />

**Comment by JinJieGu** [comment]
@jiangcb 我这边没有问题啊，请描述的更详细些，例如机型，系统版本，截图等
