### ISSUE TITLE
NullPointerException WaveLineView.java:182

### ISSUE THREAD

**Issue by maoai-xianyu** [Jay-Goo/WaveLineView#10]
您好，博主：我这边再使用控件的时候空指针异常。
![qq20180130-165345](https://user-images.githubusercontent.com/17868022/35556790-2a628c5a-05de-11e8-8b4c-b234c9d1c3ca.png)
我用的nin您的源码。

**Comment by suntiago** [comment]
我也遇到了这个问题，

**Comment by gufengpiaoyi** [comment]
我也遇到了

**Comment by qwerlh** [comment]
NullPointerException: Attempt to read from null array    我也是啊

**Comment by Blowing** [comment]
有人解决了吗

**Comment by 7puchi** [comment]
已经找到了暂时解决方案 @Blowing @qwerlh @maoai-xianyu @suntiago @gufengpiaoyi 
#23 
但是不保证其稳定性
