### ISSUE TITLE
 ?

### ISSUE THREAD

**Issue by jifuliya** [Jay-Goo/WaveLineView#13]
不劳而获真的那么安心么

**Comment by JinJieGu** [comment]
@jifuliya 首先很抱歉，这个项目确实参考了其他项目，由于我自己的疏忽忘记了添加致谢【已修正】，这个项目是我当时仿制Tencent OS录音机波形时写的另一个项目[RecordWaveView](https://github.com/Jay-Goo/RecordWaveView)，在这个项目中所有我参考的项目我是添加了致谢的。我并没有安心的不劳而获，那么多次commit也都在那里，我也为了优化它的性能和效果做了很多努力（原项目确实有好多问题），我保证这些代码都是我一行行的敲来的，哪怕那些一样的代码也是我一个个敲出来（当初是为了练习）。我的本意只是想让更多人能够更简单的使用它，并不是copy一下换个皮去骗星，也没有必要，您刺耳的字眼伤害了我的自尊，也警醒我以后类似情况要加上致谢！最后再说一声抱歉，我真不是有意的……
