### ISSUE TITLE
为什么没有振幅没有随着音量的改变而改变??

### ISSUE THREAD

**Issue by Lollipope** [Jay-Goo/WaveLineView#2]
我跑在中兴的手机上面,Android 4.3上,振幅没有随着音量的改变而改变..

**Comment by JinJieGu** [comment]
@Lollipope 请使用封装好的WaveMp3Recorder代替demo中的WaveLineView，WaveLineView本身是不含录音功能的，所以动画振幅不会随着音量的改变而改变，你可以参照WaveMp3Recorder自己进行封装
