### ISSUE TITLE
无法显示的解决办法

### ISSUE THREAD

**Issue by CodeK1988** [Jay-Goo/WaveLineView#20]
`private void startThread() {
        if (renderThread != null && !renderThread.running) {
            renderThread.setRun(true);
            try {
                if (renderThread.getState() == Thread.State.NEW) {
                    renderThread.start();
                }
            } catch (RuntimeException e) {
                e.printStackTrace();
            }
        } else {
            renderThread = new RenderThread(this);
            renderThread.setRun(true);
            renderThread.start();
        }
    }

@Override
    public void surfaceCreated(SurfaceHolder holder) {
        renderer = onCreateRenderer();
        LogUtil.e("RenderView surfaceCreated renderer:" + renderer);
        if (renderer != null && renderer.isEmpty()) {
            throw new IllegalStateException();
        }
        if (renderThread != null)
            renderThread = new RenderThread(this);
    }
`

**Comment by Blowing** [comment]
`
mWaveLineView.setVisibility(View.VISIBLE);
        mWaveLineView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {



            @Override
            public void onGlobalLayout() {
                if (mWaveLineView.getHeight() > 0) {
                    mWaveLineView.startAnim();
                }
            }
        });

`

**Comment by CodeK1988** [comment]
@Blowing 你的貌似更优雅 😀
