### ISSUE TITLE
背景透明问题

### ISSUE THREAD

**Issue by songsongtao** [Jay-Goo/WaveLineView#3]
1.默认背景为白色
2.背景颜色设置为透明,背景变成黑色
3.线条出现bug变成一条粗线

**Comment by edcedc** [comment]
我也是

**Comment by yanceyblog** [comment]
修改
@Override
    protected void doDrawBackground(Canvas canvas) {
        //绘制背景
        canvas.drawColor(backGroundColor, PorterDuff.Mode.CLEAR);
    }
