### ISSUE TITLE
背景问题

### ISSUE THREAD

**Issue by SmileChen007** [Jay-Goo/WaveLineView#4]
<jaygoo.widget.wlv.WaveLineView
        android:id="@+id/waveLineView"
        android:layout_width="match_parent"
        android:layout_height="120dp"
        app:wlvBackgroundColor="#FF4081" />
设置成其他背景
停止动画就会出现问题 波浪不显示

**Comment by CodeK1988** [comment]
@SmileChen007 
@JinJieGu 

> private void startThread() {
        LogUtil.e("RenderView startThread renderThread:" + renderThread);
        if (renderThread != null && !renderThread.running) {
            renderThread.setRun(true);
            try {
                if (renderThread.getState() == Thread.State.NEW) {
                    renderThread.start();
                }
            } catch (RuntimeException e) {
                e.printStackTrace();
            }
        } else {
            renderThread = new RenderThread(this);
            renderThread.setRun(true);
            renderThread.start();
        }
    }
